### ISSUE TITLE
Analysis tools in all tools ? 

### ISSUE THREAD

**Issue by OlivierCollin** [elixir-europe/rdm-toolkit#129]
**Description**
In the "all tools" section of the web site, the content is homogeneous and very informative. 
However, there is a first analysis tool mentioned and I fear that adding more analysis tools will make it harder for the reader to identify tools at the core of research data management. 
What is the policy about analysis tools ? Should we mention them on an other page or put a link to bio.tools ?

**Comment by floradanna** [comment]
If you are asking about "tools/softwares for data analysis", I would suggest to focus on softwares that make the analysis well documented, in open format, sharable and easily reproducible by others. An example could be R Markdown or UseGalaxy, instead of Excel.

About the "All tools and resources table", we recommend that a paragraph about when/how to use a tool/resource is first written in one of the toolkit pages, **before** adding the tool/resource into the table. For instance, before adding R Markdown or UseGalaxy in the "tools and resources table", a "Data analysis" page under "Your problem" section should be created and populated with the best practices for "What is the best way to perform data analysis?".

**Comment by OlivierCollin** [comment]
Yes, I do agree, creating a "Data analysis" page will be much more efficient. 

According to the procedure it means that I have to create an issue first ? 
After this, I can jot some ideas about reproducible tools and environments for data analysis as a starting point. 

But this will mean that a tool like Phyre2, that triggered my initial comment, does not has to be mentioned in the rdm toolkit. What are your thoughts about this ?

**Comment by floradanna** [comment]
Yes, you can create an issue about a new page for data analysis in "Your problem" section, so everyone knows your are working on it and GitHub conflicts will be avoided. Editors will create the page for you and give you the link. Then, you can edit the page and save it as draft pull request until it is ready for review. More details are in the [contribute guide](https://rdm.elixir-europe.org/github_way.html).

I am not familiar with Phyre2, but it looks like a very technique-specific tool (protein homology?). We don't have a section about techniques, but we have a section about domains, so maybe it could be listed under one of those pages, if it is used in a specific domain. Or, if Phyre2 is integrated with other tools, it could be mentioned it in a tool assembly.

You are raising a very interesting point, but I cannot give you a final answer for now. I will have to discuss this use case with the other editors. We are also trying to define our policy around tools.

**Comment by bedroesb** [comment]
I added phyre in the past as example because I was developing the bio.tools link in the tooltable, and I knew that phyre was registered in bio.tools. It is part of the RDMtool landscape list that in the beginning of the converge project was made listing all the tools/country and just picked one from there. But I agree that at this moment phyre has no use within the DM life cycle, and should propably be deleted. Sorry if adding this example caused a lot of confusion!

**Comment by OlivierCollin** [comment]
@bedroesb Don't be sorry, it raised an interesting point !
