### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by siirif** [elixir-europe/rdm-toolkit#244]
**What topic do you wish to add?**
Please provide a brief description.

Writing about how to file naming conventions. this page could be merged to some other page later if needed (e.g. with folder structure)

**Are there existing pages in the RDM toolkit website related to the requested page?**
this would go to "your problem"

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:
many guides on different library pages, could make one for this toolkit

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:
wp3 asked wp1 on to contribute, so here we are!

**Comment by floradanna** [comment]
@siirif @minnami
Hi, thank you for opening this issue and proposing the page.
Since "file naming" could belong to the more general topic "data organisation", I have created a "data organisation" page at[ this link](https://github.com/elixir-europe/rdm-toolkit/blob/master/pages/your_problem/data_organisation.md). You could add the best practices about "file naming" as one specific sub-problem in this page.

I would propose to use this page for related topics, such as "folder structure" and "file versioning", which could be written when an issue about these topics will be opened.
Please, let me know if you have a different view about the arrangement of the page for these topics.

In order to add your content, first click on the link and then on the "pencil icon" on the GitHub page, as describe in our ["Contribute guide"](https://rdm.elixir-europe.org/github_way.html#write-your-content-and-make-a-pull-request). You can save your draft as "Draft Pull Request" until the content is ready for review, as described in the guide.

Let me know if you have any questions. Thank you!
