### ISSUE TITLE
Data analysis

### ISSUE THREAD

**Issue by OlivierCollin** [elixir-europe/rdm-toolkit#294]
**What topic do you wish to add?**
As mentioned in issue #129 it could be interesting to add a new 'data analysis' page in the "your problem' section. 

**Are there existing pages in the RDM toolkit website related to the requested page?**
no

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:
no particular context

**Comment by bedroesb** [comment]
Hi, thank you for opening this issue and proposing the page.
I have created the requested page and you can find it at this [link](https://rdm.elixir-europe.org/data_analysis).

In order to add your content, first click on the link and then on the "pencil icon" on the GitHub page, as describe in our [Contribute guide](https://rdm.elixir-europe.org/how_to_contribute.html). You can save your draft as "Draft Pull Request" until the content is ready for review, as described in the guide.

Let me know if you have any questions. Thanks!
