### ISSUE TITLE
Develop the "Style Guide" 

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdm-toolkit#71]
The style guide should be written. Ideally by a native English speaker.

Would include advice such as:

- [ ] Citing other resources.  
- [ ] Text style. Use of active voice instead of passive. Avoiding latin abbreviations. Quoting 
- [ ] Using images and icons. Preferred formats and licenses.
- [ ] Cross referencing between multiple pages.

**Comment by martin-nc** [comment]
I can have a go at that. I think we'd need to keep it fairly short, and specific to the issues you might encounter when creating content for this site e.g. brand colours, icon styles, and the contentious question of whether 'data' should be treated as singular or plural! For the general stuff we could link to the EC style guide: https://ec.europa.eu/info/sites/info/files/styleguide_english_dgt_en.pdf

**Comment by pinarpink** [comment]
@martin-nc Great! And I agree shorter the better.  Looking at the issue, I realise perhaps cross-referencing and image icon use may be described in the demo page rather than the style guide.

**Comment by martin-nc** [comment]
Here as an outline of the style guide contents. I think each point will only be a line, so hopefully it won't be too long. I guess we'll have to modify it as the site progresses, too. Does that look okay?

### General
 - Writing tone (friendly, conversational rather than formal, use 'you' to speak directly to the user).
 - Writing style (short, active sentences, concrete nouns where possible, short paragraphs, make use of headings and bullet points to break text up).

### Text
 - Link to EC style guide
 - Acronyms and abbreviations (spell them out the first time - don't assume people know them!)
 - Citation style
 - 'Data' plural or singular?
 - Date and time formats
 - Emails (spell them out, don't link a word to them)
 - Headings (use hierarchically like h1, h2, h3 and not h1, h3; only the first word capitalised)
 - 'Life cycle' or 'lifecycle'? (Probably the former.)
 - Link text (don't use 'Click here')
 - Quotations

### Graphic design
 - Colours
 - Fonts
 - Templates
 - Illustrations
 - Images (including formats, sizes and positions)

### How to suggest amendments/additions to the style guide
